SRAM_SP1_CFG_INSTNAME	:= "icache_sram"
SRAM_SP1_CFG_WORDS		:= 256
SRAM_SP1_CFG_BITS 		:= 86
SRAM_SP1_CFG_FREQUENCY	:= 500
SRAM_SP1_CFG_MUX 		:= 4

SRAM_SP2_CFG_INSTNAME	:= "data_sram"
SRAM_SP2_CFG_WORDS		:= 2048
SRAM_SP2_CFG_BITS 		:= 32
SRAM_SP2_CFG_MASK_SIZE	:= 8
SRAM_SP2_CFG_FREQUENCY 	:= 500
SRAM_SP2_CFG_MUX 		:= 8